name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      run: echo build
  
  test:
    runs-on: ubuntu-latest

    steps:
      run: echo test

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      run: echo deploy
  
